fixtures:
  repositories:
    epel: 'https://github.com/voxpupuli/puppet-epel.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    vcsrepo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    cron_core:
      repo: https://github.com/puppetlabs/puppetlabs-cron_core.git
      puppet_version: ">= 6.0.0"
