---
# yamllint disable rule:line-length rule:truthy
os: linux
dist: focal
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
jobs:
  fast_finish: true
  include:
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=test
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian9-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian9-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=fedora30-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=fedora30-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=fedora31-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=fedora31-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  username: puppet
  password:
    secure: "n/CVUS2upgv5DifCm/YsjBxR/11bdTRDYi1x9QK6ILa32+6ngVV2RQaIMXXJfJKYIPT8/O21tpc9C7fOBRGhRpNbl0usfvqsZS0C9UkpEx6AqT7lcRzj6pLrNn3IuChhZ0tQjNiKp9LxVTzltxr5uTFwKKCE4o534v/DLAzkzq5EAZuBWpRS1rcVHQA3o0767Gu3601yyYkZj9ySDH5RpbSdTCcNkTzwtFhr2NEvVb+2FI0RhchDSqPBfNWHV4Hn3dKuL42MNC2zjd2FYFpC8F27OXk/erUZIOZFfpZuIWypjSimfVC95a2Nb8kfQotTvQxUI1fwiB01ibUQGGkJj+mh7Utg/byBrbijpJnWRR7TT6oQ1NbIUHVXcqE1tfpbCBZ4Ws2Hqji0QoGc0fMrkt1NVlZlgbVrb9t+ctb1QcLaEPI+1Zf2a3AZhXOKA1EGx2W5DTQSWSPv57BUtFPICZENQi/ats30h+0FwtN7rjfx8Q6BIGO2D5JODI6eJC0nLNaL5UaPA0pjGRsNlZWoUzieuKG08G/rQtj/8jLq/3eLICv1cbfvj7lDPc0thPwXdrPIC9nLSisb/wdLufpqXsFku9TeBqrRHfQWImybcv7JRAeZZeHEo+tvFvZg5MSAEiPmz8zIOJOKhuMKEXlOmALmSjEhW6Ca5r7xuQ5Qwm0="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
